name: "build"

on: 
  push:
    branches:
      - "*"

concurrency:
  group: "build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-library:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version-file: .github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          add-job-summary: on-failure
      - name: "build"
        run: |
          cd lib
          ./gradlew build
  
  build-example:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version-file: .github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          add-job-summary: on-failure
      - name: "build"
        run: |
          cd example
          ./gradlew build
